### ISSUE TITLE
ArrayBuilder is off-by-one (off-by-some?)

### ISSUE THREAD

**Issue by PerilousApricot** [spark-root/laurelin#45]
(reported by @lgray)

A certain ROOT file has its first 3 baskets with the following offsets: `long[] basketEntryOffsets = {0, 1000, 4266, 8532}`. The ArrayBuilder is able to load the 1st basket OK, but the 2nd and subsequent basket fail at the last line of the following snippet

https://github.com/PerilousApricot/spark-ttree/blob/bd3a137775bad8d0727ffd3b70c7c2fb26337b7f/src/main/java/edu/vanderbilt/accre/laurelin/array/ArrayBuilder.java#L186-L193

I've (screenshot because I'm trying to get on a bus) copied the locals for the 0th and 1st baskets:

<img width="385" alt="Screen Shot 2019-07-25 at 5 19 16 PM" src="https://user-images.githubusercontent.com/93354/61912702-7f2c9600-af00-11e9-83cc-ec62cead82af.png">
<img width="383" alt="Screen Shot 2019-07-25 at 5 19 44 PM" src="https://user-images.githubusercontent.com/93354/61912705-82278680-af00-11e9-9456-21d06fabf24a.png">

I can't quite make heads or tails of what the code is supposed to do (what is `j`?) -- The basketstart and basketstop appear to be correct on the 2nd iteration (1 & 2), and the code is trying to access the offsets via the index 1&2, but the constructor strips out the unnecessary elements from basket offsets before it passes it along to the callable, so the correct indices it should access is 0&1.

I remember you saying that taht code was super tricky and a copy-paste from the python version, so I'm scared to mess with it too much. Indeed, a couple of easy changes (adding/subbing 1 to indices) caused other tests to bomb, so all the index arithmetic is indeed fragile. Could you take a look?

The reproducer can be found at: https://github.com/PerilousApricot/spark-ttree/blob/bug/off-by-one/src/test/java/edu/vanderbilt/accre/array/ArrayBoundsTest.java -- but I can give the reproducer with the full file if that helps (it's a 100MB file, so I figured it was more helpful to dial things out)

**Comment by PerilousApricot** [comment]
I should mention, the actual error is an array index exception `basket_entryoffset[i + 1]` was resolving to `basket_entryoffset[2]`

**Comment by jpivarski** [comment]
@jpivarski to remind myself to do this soon.

**Comment by jpivarski** [comment]
Take a look at that PR. It's not successful, but I think it's in your hands now.
